### ISSUE TITLE
SC 143 -- Contrast of button text

### ISSUE THREAD

**Issue by damiansian** [newjersey/accessibility-pm#15]
## URL 
https://demo.fileyourstatetaxes.org/en/questions/contact-preference

## Issue
The back button has text lower than 4.5:1 for small text. 

## Screen shot
![Image](https://github.com/user-attachments/assets/8d700230-633c-450e-8730-c17c05091e30)

## WCAG
[SC 1.4.3: Contrast (Minimum) (Level AA)](https://w3.org/TR/WCAG21#contrast-minimum)

## User impact
Users with low vision benefit from stronger contrast in the user interface. 

### Option one: (recommended)
Darken the text and arrow from `#757575` to `#2D2D2D`.

```css
.question-layout .back a, .question-layout .back .button--link {
    font-size: 1.6rem;
    border: 1px solid #2d2d2d;
    border-radius: 4px;
    background: #F7F7F7;
    padding: .75rem 1rem;
    color: #2d2d2d;
    text-decoration: none;
}
``` 

![Image](https://github.com/user-attachments/assets/efeb80a0-29cd-48f8-a321-7f70d2eaaa2f)

### Option two: (not recommended)
Increase the size of the text to 24 pixels.
