### ISSUE TITLE
WHCM -- Windows High Contrast Mode Support

### ISSUE THREAD

**Issue by damiansian** [newjersey/accessibility-pm#5]
## URL 
https://demo.fileyourstatetaxes.org/

## Issue
On a PC, or simulated in a browser using the rendering options, turning on Windows High Contrast Mode leads to two errors on the home page. 

### Issue one:
The link opens in new window icon disappears. 

### Issue two: 
The focus indicator isn't visible. 

## WCAG
n/a 

> [!IMPORTANT]  
> This is a Section 508 requirement to support OS level accessibility options. Since the State of NJ is required to meet Section 508, this is a requirement. 

## User Impact
Users utilize Windows high contrast mode primarily to enhance the visibility and readability of text and interface elements on their screen, particularly those with visual impairments like low vision or color blindness, as it drastically increases the contrast between colors, making it easier to distinguish between different parts of the interface; essentially, it simplifies the visual display by using stark color combinations like black text on a white background or vice versa. 

## Screen walkthrough
https://github.com/user-attachments/assets/8cf383e0-55bd-4e88-b669-bb3a394ada01

### SVG
To fix an SVG not respecting Windows High Contrast Mode (forced colors), use the CSS property "currentColor" within your SVG elements for fills and strokes, which will automatically inherit the system color set by the user's high contrast mode settings; if necessary, you can further refine styling using media queries targeting the "forced-colors" state to ensure proper color adjustments in high contrast mode. 

### Visible focus indicators

```css
@media (forced-colors: active) {
  input:focus {
    outline: 2px solid system-color:highlight;
  }

  button:focus {
    background-color: system-color:highlight;
  }
}
```

**Comment by tchangCfA** [comment]
CfA will work on this

**Comment by mrotondo** [comment]
Hi @damiansian, thanks for filing this. Where did the example code under the "Visible focus indicators" come from? The css there isn't working for me, and I want to make sure I'm understanding the proposed solution so that I can fix this issue appropriately.

**Comment by mrotondo** [comment]
Hi again - I can reproduce the issue with the SVG icons for external links disappearing under forced colors emulation, but I can't resolve it using any of the proposed resolutions - no matter what I set any of the css attributes to, the icon simply disappears in Windows High Contrast mode. I've observed the same behavior on the [USWDS design guide site](https://designsystem.digital.gov/components/link/), as well as their [official design system site](https://designsystem.digital.gov/), and on the [wikipedia page for external link icons](https://en.wikipedia.org/wiki/Help:External_link_icons), leading me to believe that this issue is widespread. Do you have any recommendations for other resolutions we can try?

**Comment by damiansian** [comment]
@mrotondo 

I have created a CodePen to demonstrate the focus indicator and svg coloring in Windows High Contrast Mode. 
[CodPen](https://codepen.io/dsian108/pen/vEYpJvy)

Read more on WHCM styling here: 
[Windows Help on WHCM](https://blogs.windows.com/msedgedev/2020/09/17/styling-for-windows-high-contrast-with-new-standards-for-forced-colors/)

## SVG
To ensure SVG icons remain visible in both normal and Windows High Contrast modes, implement the following pattern:

```html
<a href="..." target="_blank" class="external-link">
    Link Text
    <svg viewBox="0 0 12 12" xmlns="http://www.w3.org/2000/svg">
        <path fill="currentColor" d="M2,2v8h8V7h1v4H1V1h4v1H2z M7,1h4v4h-1V2.7L5.7,7L5,6.3L9.3,2H7V1z"/>
    </svg>
</a>
``` 

```css
.external-link svg {
    width: 12px;
    height: 12px;
    margin-left: 4px;
    vertical-align: middle;
}

@media (forced-colors: active) {
    .external-link svg {
        fill: ButtonText;
    }
}
``` 
### Key Points:
1. Use `fill="currentColor"` in the SVG path
2. In forced colors mode, set `fill: ButtonText` (or whatever makes sense in your WHCM color scheme) to use system colors
3. Avoid `forced-color-adjust: none` as it prevents proper high contrast adaptation

This implementation ensures the icon remains visible in all contrast modes while maintaining proper color relationships with surrounding text.

## Focus Styles in Windows High Contrast Mode
Here's how we ensure accessible focus indicators that work in both normal and Windows High Contrast Mode:
CSS Implementation:
```css
/* Button focus styles */
button:focus {
    outline: 2px solid #0066cc;    /* Default focus ring */
    outline-offset: 2px;
}

@media (forced-colors: active) {
    button:focus {
        outline: 2px solid Highlight;    /* System highlight color in WHCM */
        outline-offset: 2px;
    }
}

/* Link focus styles */
a:focus {
    outline: 2px solid #0066cc;
    outline-offset: 2px;
}

@media (forced-colors: active) {
    a:focus {
        outline: 2px solid Highlight;
    }
}
``` 
### Key Points:
1. Use outline instead of box-shadow for focus indicators (outlines are always visible in WHCM)
2. In forced colors mode, use the system Highlight color to ensure focus indicators remain visible
3. Maintain consistent outline-offset across modes for predictable spacing
4. Apply these patterns to both links and buttons for consistent focus behavior

This implementation ensures:
- Focus indicators meet WCAG 2.4.7 (Focus Visible)
- Consistent appearance across normal and high contrast modes
- Proper contrast against any background color or pattern
- Reliable visibility for keyboard navigation

The system Highlight color in WHCM is specifically designed to stand out against any background, making it the ideal choice for focus indicators in high contrast scenarios.


## Screen grabs

Focus on link working and the SVG is colored correctly in WHCM. 
![focus WHCM on link working and svg colored correctly](https://github.com/user-attachments/assets/42f43bd4-0978-4b42-884c-9ac6e7a54f6b)

Focus on buttons in WHCM
![Focus on button in WHCM working perfectly](https://github.com/user-attachments/assets/22cd410a-b360-458b-8f36-5670ba4dc54d)

## Other gov sites implementation
You have pointed out that those sites are out of compliance Section 508. Maybe we can submit the solution to them somehow? Section 508 states:

> 502.2.2 No Disruption of Accessibility Features: Software shall not disrupt platform features that are defined in the platform documentation as accessibility features.

Windows High Contrast Mode is a platform (i.e., operating system) accessibility feature so this has standing for a conformance requirement in the federal government and agencies that receive federal funding. To boot, the State of NJ's accessibility policy states conformance to Section 508. 

>Our services have adopted Section 508 and W3C Web Accessibility Initiative standards and guidelines as the benchmark to meet the objectives of the Universal Accessibility for State Web sites policy.
[NJ a11y policy](https://www.njportal.com/errorpages/Accessibility.aspx)
