### ISSUE TITLE
SC 247 -- Visible focus indicator missing on accordion

### ISSUE THREAD

**Issue by damiansian** [newjersey/accessibility-pm#9]
## URL 
https://demo.fileyourstatetaxes.org/en/nj/landing-page

## Issue
The accordions/disclosure components have no visible focus indicators for keyboard focus. 

## WCAG
[SC 2.4.7: Focus Visible (Level AA)](https://w3.org/TR/WCAG21#focus-visible):

## User impact
Sighted users with physical disabilities that rely on keyboards to operate digital interfaces need a visible focus indicator to understand what control has focus so it can be operated.  

### Should be
```css
.xxx:focus {
    box-shadow: 0 0 0 5px #21C834,inset 0px 2px 0px rgba(0,0,0,0.15)
}
```
